on: [push]

name: Cargo

jobs:
  ARM64:
    name: ARM64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Release for arm64        
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          # @TODO: eventually we need to get this to work on ubuntu20.04 for build parity but we are using
          # 18.04 because it was easier to get working, apparently there is a bug in 20.04s gpg?
          distro: ubuntu18.04
          githubToken: ${{ github.token }}  
          install: |            
            apt update && apt -y install libvips-dev
          run: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh            
            cargo build --release --manifest-path thumbnail-test/rust-perftest/Cargo.toml