on: [push]

name: Cargo

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:    
      - name: Install libvips-dev
        run: sudo apt-get install -y libvips-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --manifest-path thumbnail-test/rust-perftest/Cargo.toml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rust-perftest
          path: thumbnail-test/rust-perftest/target/release/rust-perftest
          retention-days: 1          